export const testList = [
  {
    text: "Quick introduction to Markdown (press Ctrl/Cmd + S to save):",
    element: "h1",
  },
  { text: "Subtitles", element: "h2" },
  { text: "Subtitle", element: "div" },
  { text: "Bulleted list", element: "h2" },
  { text: "first bulleted item", element: "li" },
  { text: "second bulleted item", element: "li" },
  { text: "Numbered list", element: "h2" },
  { text: "first item", element: "li" },
  { text: "second item", element: "li" },
  { text: "Tasklist", element: "h2" },
  { text: "to do", element: "li" },
  { text: "done", element: "li" },
  { text: "Links", element: "h2" },
  { text: "This", element: "a" },
  { text: "is an example link", element: "div" },
  { text: "Autolink literals", element: "h2" },
  { text: "www.example.com", element: "a" },
  { text: "https://example.com", element: "a" },
  { text: "contact@example.com", element: "a" },
];
